package fr.uge.Xplain.dataBase.message;

import io.smallrye.common.annotation.RunOnVirtualThread;
import org.jdbi.v3.sqlobject.config.RegisterRowMapper;
import org.jdbi.v3.sqlobject.customizer.Bind;
import org.jdbi.v3.sqlobject.statement.GetGeneratedKeys;
import org.jdbi.v3.sqlobject.statement.SqlQuery;
import org.jdbi.v3.sqlobject.statement.SqlUpdate;

import java.util.List;



@RegisterRowMapper(MessageMapper.class)
@RunOnVirtualThread
public interface MessageDao {
   /**
    * Inserts a new message into the messages table in the database.
    *
    * @param conversationId the unique identifier of the conversation to which the message belongs
    * @param sender the name or identifier of the entity sending the message; can either be "user" or "LLM"
    * @param content the textual content of the message
    * @param messageType the type of the message, such as "USER" or "LLM"
    * @param errorsCompiler a string representing any errors or issues related to the message compilation
    * @param responseLLM the response text generated by the LLM (Large Language Model) associated with the message
    * @return the unique identifier of the newly inserted message in the messages table
    */
   @SqlUpdate("INSERT INTO messages (conversationId, sender, content, messageType, errorsCompiler, responseLLM) " +
              "VALUES (:conversationId, :sender, :content, :messageType, :errorsCompiler, :responseLLM)")
   @GetGeneratedKeys
   long insertMessage(
       @Bind("conversationId") long conversationId,
       @Bind("sender") String sender,
       @Bind("content") String content,
       @Bind("messageType") String messageType,
       @Bind("errorsCompiler") String errorsCompiler,
       @Bind("responseLLM") String responseLLM
   );

   /**
    * Retrieves all messages associated with a specific conversation from the database.
    * The messages are ordered by their creation timestamp.
    *
    * @param conversationId the unique identifier of the conversation for which messages are to be retrieved
    * @return a list of Message objects associated with the given conversationId, ordered by their creation time
    */
   @SqlQuery("SELECT * FROM messages WHERE conversationId = :conversationId ORDER BY createdAt")
   List<Message> getMessagesByConversationId(@Bind("conversationId") long conversationId);
}
