-- Création de la table "conversation"
CREATE TABLE conversation (
                              id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              title VARCHAR(255) NOT NULL,
                              created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Création de la table "message"
CREATE TABLE message (
                         id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         conversation_id INTEGER NOT NULL,
                         sender VARCHAR(255) NOT NULL,
                         content VARCHAR(255) NOT NULL,
                         response_llm VARCHAR(255),
                         errors_compiler VARCHAR(255),
                         created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                         FOREIGN KEY (conversation_id) REFERENCES conversation (id)
);