package fr.uge.Xplain.dataBase;

import fr.uge.Xplain.dataBase.conversation.Conversation;
import fr.uge.Xplain.dataBase.conversation.ConversationDao;
import fr.uge.Xplain.dataBase.message.Message;
import fr.uge.Xplain.dataBase.message.MessageDao;
import io.agroal.api.AgroalDataSource;
import io.quarkus.arc.InjectableInstance;
import io.smallrye.common.annotation.RunOnVirtualThread;
import jakarta.annotation.PostConstruct;
import jakarta.inject.Inject;
import jakarta.enterprise.context.ApplicationScoped;
import org.jdbi.v3.core.Jdbi;
import org.jdbi.v3.sqlobject.SqlObjectPlugin;

import java.time.LocalDateTime;
import java.util.List;

@ApplicationScoped
@RunOnVirtualThread
public class DataBaseService {

  /**
   * Represents the data source used for database operations within the application.
   * This field is automatically injected and provides a connection pool for interacting
   * with the database in a resource-efficient manner.
   *
   * The data source is configured to enable SQL queries and transactions for operations such as
   * creating, updating, and retrieving data related to conversations and messages.
   *
   * It is managed and initialized by the container and ensures proper resource allocation and
   * connection management.
   */
  @Inject
  InjectableInstance<AgroalDataSource> dataSource;

  /**
   * Represents an instance of the DatabaseInitializer class used for initializing
   * and configuring the database schema, including creating tables and defining
   * their relationships. The DatabaseInitializer ensures that necessary database
   * structures, such as tables for conversations and messages, exist at the
   * application startup.
   *
   * This field is injected into the containing class to facilitate database
   * initialization and potentially to verify or debug the current database state.
   */
  @Inject
  DatabaseInitializer databaseInitializer;

  /**
   * This field represents the Jdbi instance used for database interactions in the
   * {@code DataBaseService} class. Jdbi is a lightweight database abstraction
   * library that simplifies working with relational databases in Java. The instance
   * is used for executing SQL statements, mapping results to objects, and managing
   * transactions within the service.
   */
  private Jdbi jdbi;

  /**
   * Initializes the Jdbi instance and configures it with the required plugins.
   * This method is executed after the dependency injection is completed, using the
   * @PostConstruct annotation.
   *
   * The initialization includes:
   * - Creating a Jdbi instance with the provided data source.
   * - Installing the SqlObjectPlugin for SQL object support.
   * - Verifying the database tables through the databaseInitializer.
   * - Printing the current status of the database tables for validation purposes.
   */
  @PostConstruct
  public void init() {
    this.jdbi = Jdbi.create(dataSource.get());
    this.jdbi.installPlugin(new SqlObjectPlugin());
    databaseInitializer.verifyTables();
    databaseInitializer.printTableStatus();
  }



  /**
   * Creates a new conversation with the specified title and stores it in the database.
   *
   * @param title the title of the new conversation to be created
   * @return a {@code Conversation} object representing the newly created conversation,
   *         including its ID, title, and creation timestamp
   */
  public Conversation createConversation(String title) {
    long conversationId = jdbi.withExtension(ConversationDao.class,
            dao -> dao.createConversation(title));
    return new Conversation(conversationId, title, "", LocalDateTime.now());
  }

  /**
   * Adds a new message to an existing conversation.
   *
   * @param conversationId the unique identifier of the conversation to which the message belongs
   * @param sender the name or identifier of the entity sending the message; can either be "user" or "LLM"
   * @param content the textual content of the message
   * @param errorsCompiler a string representing any errors or issues related to the message compilation
   * @param responseLLM the response text generated by the LLM (Large Language Model) associated with the message
   * @return the newly created Message object containing all relevant details of the added message
   */
  public Message addMessageToConversation(long conversationId, String sender, String content, String errorsCompiler,
                                          String responseLLM) {
    return jdbi.withExtension(MessageDao.class, dao -> {
      long messageId = dao.insertMessage(
              conversationId,
              sender,
              content,
              sender.equals("user") ? "USER" : "Marx",
              errorsCompiler,
              responseLLM);
      return new Message(
              messageId,
              conversationId,
              sender,
              content,
              sender.equals("user") ? "USER" : "Marx",
              LocalDateTime.now(),
              errorsCompiler,
              responseLLM);
    });
  }

  /**
   * Retrieves all messages associated with a specific conversation from the database.
   *
   * @param conversationId the unique identifier of the conversation for which messages are to be retrieved
   * @return a list of Message objects associated with the given conversationId, ordered by their creation time
   */
  public List<Message> getConversationMessages(long conversationId) {
    return jdbi.withExtension(MessageDao.class,
            dao -> dao.getMessagesByConversationId(conversationId));
  }

  /**
   * Retrieves a list of all conversations stored in the database.
   * If an error occurs during the operation, an empty list is returned.
   *
   * @return a list of {@code Conversation} objects, ordered by their creation date in descending order.
   *         The list will be empty in case of an exception or if no conversations are found.
   */
  public List<Conversation> getAllConversations() {
    try {
      // Si aucune exception ne survient, retourne les résultats normaux
      return jdbi.withExtension(ConversationDao.class, ConversationDao::getAllConversations);
    } catch (Exception e) {
      // Retourne une liste vide en cas d'erreur
      System.err.println("Error fetching conversations: " + e.getMessage());
      return List.of(); // Retourne une liste vide au lieu de relancer l'exception
    }
  }

  /**
   * Updates the title of a conversation in the database using the first message's content.
   * The new title is derived from the first 25 characters of the content of the first message,
   * if messages exist for the conversation. If there are no messages, the title is not updated.
   *
   * @param conversationId the ID of the conversation whose title is to be updated
   */
  public void updateConversationTitleWithFirstMessage(long conversationId) {
    jdbi.useTransaction(handle -> {
      MessageDao messageDao = handle.attach(MessageDao.class);
      ConversationDao conversationDao = handle.attach(ConversationDao.class);

      List<Message> messages = messageDao.getMessagesByConversationId(conversationId);

      if (!messages.isEmpty()) {
        // Vérification sécurisée pour le "titre"
        var firstMessage = messages.getFirst(); // Récupérer le premier message
        var firstContent = firstMessage.content();
        if (firstContent != null && !firstContent.isEmpty()) {
          var newTitle = firstContent.substring(0, Math.min(25, firstContent.length()));
          conversationDao.updateConversationTitle(conversationId, newTitle);
        }

        if (messages.size() > 2) {
          var thirdMessage = messages.get(2);
          if (thirdMessage != null) {
            var thirdContent = thirdMessage.content();
            if (thirdContent != null && !thirdContent.isEmpty()) {
              var description = thirdContent.substring(0, Math.min(150, thirdContent.length()));
              conversationDao.updateConversationDescription(conversationId, description);
            }
          }
        }
      }
    });
  }

  /**
   * Updates the last modified date of a conversation identified by its ID.
   *
   * @param conversationId the unique identifier of the conversation whose "createdAt" timestamp needs to be updated
   */
  public void updateConversationDate(long conversationId) {
    jdbi.useTransaction(handle -> {
      ConversationDao conversationDao = handle.attach(ConversationDao.class);
      conversationDao.updateConversationDate(conversationId);
    });
  }

  /**
   * Deletes a conversation from the database based on the specified conversation ID.
   *
   * @param conversationId the unique identifier of the conversation to be deleted
   */
  public void deleteConversation(long conversationId) {
    jdbi.useTransaction(handle -> {
      ConversationDao conversationDao = handle.attach(ConversationDao.class);
      conversationDao.deleteConversation(conversationId);
    });
  }

  /**
   * Updates the title of a conversation in the database.
   *
   * @param conversationId the unique identifier of the conversation to be updated
   * @param title the new title to set for the conversation
   */
  public void updateConversationTitle(long conversationId, String title) {
    jdbi.useTransaction(handle -> {
      ConversationDao conversationDao = handle.attach(ConversationDao.class);
      conversationDao.updateConversationTitle(conversationId, title);
    });
  }

  public Conversation getConversationById(long id){
    return jdbi.withExtension(ConversationDao.class, dao -> dao.getConversationById(id));
  }


}