package fr.uge.Xplain.dataBase;

import io.agroal.api.AgroalDataSource;
import io.quarkus.arc.InjectableInstance;
import io.smallrye.common.annotation.RunOnVirtualThread;
import jakarta.annotation.PostConstruct;
import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;

import java.sql.SQLException;
import java.util.Objects;
import java.util.logging.Logger;

@ApplicationScoped
@RunOnVirtualThread
public class DatabaseInitializer {
    private static final Logger LOG = Logger.getLogger(DatabaseInitializer.class.getName());


    @Inject
    InjectableInstance<AgroalDataSource> dataSource;

    @PostConstruct
    void init() {
        try (var conn = dataSource.get().getConnection()) {
            try (var stmt = conn.createStatement()) {
                // Configuration HSQLDB spécifique
                stmt.execute("SET DATABASE SQL SYNTAX ORA TRUE");


                // Création de la table conversations
                stmt.execute("""
                CREATE TABLE IF NOT EXISTS conversations (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    title VARCHAR(255) NOT NULL,
                    description VARCHAR(1000),
                    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                )
            """);

                // Création de la table messages
                stmt.execute("""
                CREATE TABLE IF NOT EXISTS messages (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    conversationId INTEGER,
                    sender VARCHAR(255) NOT NULL,
                    content LONGVARCHAR NOT NULL,
                    messageType VARCHAR(50) NOT NULL,
                    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    errorsCompiler LONGVARCHAR,
                    responseLLM LONGVARCHAR,
                    FOREIGN KEY (conversationId) REFERENCES conversations(id) ON DELETE CASCADE
                )
            """);
            }
        } catch (SQLException e) {
            LOG.severe("Failed to initialize database: " + e.getMessage());
            throw new RuntimeException("Failed to initialize database: " + e.getMessage(), e);
        }
    }


    // Méthode utile pour le debug
    public void printTableStatus() {
        try (var conn = dataSource.get().getConnection()) {
            var meta = conn.getMetaData();
            var tables = meta.getTables(null, "PUBLIC", null, new String[]{"TABLE"});
            
            if (Objects.isNull(tables)) {
                System.out.println("Aucune table trouvée.");
                return; // Sortir si aucune table n'est trouvée
            }
            
            System.out.println("=== Tables existantes ===");
            while (tables.next()) {
                String tableName = tables.getString("TABLE_NAME");
                System.out.println("Table trouvée: " + tableName);

                // Affiche les colonnes de chaque table
                var columns = meta.getColumns(null, "PUBLIC", tableName, null);
                while (columns.next()) {
                    System.out.println(" - " + columns.getString("COLUMN_NAME") +
                            " (" + columns.getString("TYPE_NAME") + ")");
                }
            }
        } catch (SQLException e) {
            LOG.severe("Failed to initialize database: " + e.getMessage());
            throw new RuntimeException("Failed to initialize database: " + e.getMessage(), e);
        }
    }

    // Optionnel : méthode pour vérifier que les tables existent
    public void verifyTables() {
        try (var conn = dataSource.get().getConnection()) {
            var meta = conn.getMetaData();
            var tables = meta.getTables(null, null, null, new String[]{"TABLE"});
            System.out.println("Tables existantes dans la base de données :");
            while (tables.next()) {
                System.out.println(" - " + tables.getString("TABLE_NAME"));
            }
        } catch (SQLException e) {
            throw new RuntimeException("Failed to verify tables", e);
        }
    }
}