package fr.uge.Xplain.llm;

import com.github.tjake.jlama.model.ModelSupport;
import io.smallrye.common.annotation.RunOnVirtualThread;
import jakarta.websocket.Session;
import jakarta.annotation.PostConstruct;
import jakarta.annotation.PreDestroy;
import jakarta.enterprise.context.ApplicationScoped;
import com.github.tjake.jlama.safetensors.DType;
import com.github.tjake.jlama.model.AbstractModel;
import com.github.tjake.jlama.safetensors.prompt.PromptContext;
import org.eclipse.microprofile.config.inject.ConfigProperty;

import static com.github.tjake.jlama.safetensors.SafeTensorSupport.maybeDownloadModel;
import static com.github.tjake.jlama.model.ModelSupport.loadModel;

import java.io.File;
import java.io.IOException;
import java.util.*;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.logging.Logger;

@ApplicationScoped
@RunOnVirtualThread
public class LLMService {

  /**
   * A logger instance used for logging messages and debugging information
   * within the {@code LLMService} class. This logger is specific to the
   * scope and operations of this class and helps in tracking the execution
   * flow, capturing errors, and providing runtime diagnostics.
   */
  private static final Logger LOG = Logger.getLogger(LLMService.class.getName());



  /**
   * The default working directory path where the application stores and retrieves model files.
   * This constant is used primarily for locating the directory containing pre-trained models
   * or other related assets required during runtime.
   */
  private static final String WORKING_DIRECTORY = "./models";


  /**
   * Represents the maximum number of tokens that the language model is allowed to process in a single operation.
   * This value is configurable and is loaded from the application configuration property `llm.max.tokens`.
   * It determines the upper limit of input or output text size within the context of interaction with the language model.
   * The default value is set to 500 if no specific configuration is provided.
   */
  @ConfigProperty(name = "llm.max.tokens", defaultValue = "900")
  int maxTokens;

  /**
   * Represents the temperature parameter for the LLM service configuration.
   *
   * This variable defines the randomness of responses generated by the language model.
   * Higher values (e.g., 1.0) produce more random outputs, while lower values (e.g., 0.0)
   * make the outputs more deterministic. The value is configurable via the application
   * properties file or the corresponding default value.
   *
   * Configuration:
   * - Property name: llm.temperature
   * - Default value: 0.5
   */
  @ConfigProperty(name = "llm.temperature", defaultValue = "0.2")
  float temperature;

  @ConfigProperty(name = "llm.executor.thread.pool.size", defaultValue = "4")
  int threadPoolSize;

  private static final ExecutorService llmExecutor = Executors.newFixedThreadPool(4);


    public enum ModelType {

      MISTRAL_7B("tjake/Mistral-7B-Instruct-v0.3-Jlama-Q4"),
      Yi_Coder("tjake/Yi-Coder-1.5B-Chat-Jlama"),
      //Qwen2("tjake/Qwen2.5-0.5B-Instruct-JQ4");
      Llama_32("tjake/Llama-3.2-3B-Instruct-JQ4");

      private final String modelPath;

      ModelType(String modelPath) {
        this.modelPath = modelPath;
      }

      public String getModelPath() {
        return modelPath;
      }
  }

  /**
   * A map holding the loaded models used by the LLMService. The key represents the type of the model, as defined by the
   * {@link ModelType} enum, while the value is an instance of {@link AbstractModel}, representing the associated
   * loaded model.
   *
   * This variable supports operations within the service such as model initialization, switching between different
   * models, and accessing currently available models.
   */
  private final HashMap<ModelType, AbstractModel> loadedModels = new HashMap<>();
  /**
   * Represents the currently active model for the LLMService.
   * This variable holds the selected ModelType which is used to process
   * and generate outputs based on the model's capabilities.
   *
   * The `currentModel` field is configured at runtime and can be updated
   * via methods in the LLMService class to switch between different
   * available models. This supports flexibility in choosing an underlying
   * model suited for specific tasks.
   *
   * Possible values are defined in the ModelType enumeration, which includes:
   * - LLAMA_32
   * - MISTRAL_7B
   * - TINY_LLAMA
   *
   * Each model is backed by a specific configuration and is designed for
   * specific performance and accuracy requirements.
   */
  private ModelType currentModel;

  /**
   * Initializes the LLMService by setting the default model and loading it into memory.
   * This method is executed automatically after the construction of the bean, as indicated by the @PostConstruct annotation.
   *
   * @throws IOException if an error occurs during the loading of the default model.
   */
  @PostConstruct
  void init() throws IOException {
    LOG.info("Starting model initialization...");
    for (ModelType modelType : ModelType.values()) {
      loadModel(modelType);
      LOG.info("Model " + modelType + " loaded successfully");
    }
    LOG.info("Model initialization completed. " + loadedModels.size() + " models loaded.");
  }

  /**
   * Releases resources for all loaded models in the application.
   * This method is annotated with @PreDestroy and is automatically invoked
   * before the bean is destroyed, ensuring proper cleanup processes are executed.
   * During the cleanup process, an information log is generated for every model
   * resource that is released.
   */
  @PreDestroy
  void cleanup() {
    for (var model : loadedModels.values()) LOG.info("Model resources released");
  }


  /**
   * Loads the specified model into memory. If the model is not already loaded,
   * it checks whether the model is available locally. If the model is not present locally,
   * it attempts to download it.
   *
   * @param modelType the type of the model to be loaded. Must not be null.
   * @throws IOException if an error occurs during model loading or downloading.
   */
  private void loadModel(ModelType modelType) throws IOException {
    if (!loadedModels.containsKey(modelType)) {
      File modelDir = new File(WORKING_DIRECTORY, modelType.getModelPath());
      /**
       * Represents the current model used in the LLMService for generating
       * responses or processing tasks. This variable facilitates interaction
       * and behavior customization depending on the selected model instance.
       *
       * The model is expected to be an implementation of the AbstractModel class,
       * enabling flexibility in terms of extending functionality for different
       * model types.
       *
       * Responsible for defining the model-related behavior of the service and
       * influencing outputs generated by various service methods.
       */
      AbstractModel model;
      if (modelDir.exists() && Arrays.stream(Objects.requireNonNull(modelDir.listFiles())).anyMatch(f -> f.getName().equals("model.safetensors"))) {
      // Le modèle existe déjà localement
        LOG.info(modelDir + " existe ??");
        model = ModelSupport.loadModel(modelDir, DType.F32, DType.I8);
      } else {
        // Téléchargement nécessaire
        LOG.info("Model " + modelType + " Téléchargement nécessaire");

        File localModelPath = maybeDownloadModel(WORKING_DIRECTORY, modelType.getModelPath());
        model = ModelSupport.loadModel(localModelPath, DType.F32, DType.I8);
      }
      loadedModels.put(modelType, model);
      LOG.info("Model " + modelType + " loaded successfully");
    }
  }

  /**
   * Sets the current model to the specified {@code modelType}.
   * If the model is not already loaded, it triggers the loading process.
   *
   * @param modelType the desired model type to be set
   * @throws IOException if an I/O error occurs during the loading of the model
   */
  public void setModel(ModelType modelType) throws IOException {
    if (!loadedModels.containsKey(modelType)) {
      loadModel(modelType);
    }
    currentModel = modelType;
    LOG.info("Switched to model: " + modelType);
  }

  /**
   * Retrieves the currently active language model.
   *
   * @return the current {@code ModelType} used by the LLMService.
   */
  public ModelType getCurrentModel() {
    return currentModel;
  }

  /**
   * Retrieves all available models defined as constants in the {@code ModelType} enumeration.
   *
   * @return an array of {@code ModelType} instances, representing the available models.
   */
  public ModelType[] getAvailableModels() {
    return ModelType.values();
  }




  private String buildMistralPrompt(String javaClassContent, String errorMessage) {
    return """
        [INST] You are a Java expert. Fix this code:
        CODE:
        %s
        
        ERRORS:
        %s
        
        Provide:
        1. Brief error explanation
        2. Fixed code between ```java and ```
        [/INST]
        """.formatted(javaClassContent, errorMessage);
  }

  private String buildYiCoderPrompt(String javaClassContent, String errorMessage) {
    return """
        <|im_start|>system
        You are a specialized Java programming assistant.
        <|im_end|>
        <|im_start|>user
        Fix this Java code:
        %s
        
        Compiler errors:
        %s
        <|im_end|>
        <|im_start|>assistant
        I'll analyze and fix the code. Return format:
        - Quick error summary
        - Corrected code in ```java blocks
        <|im_end|>
        """.formatted(javaClassContent, errorMessage);
  }

  private String buildLlamaPrompt(String javaClassContent, String errorMessage) {
    return """
        ### System: You are a Java expert who fixes code errors.
        ### Human: Fix this Java code that has errors:
        %s
        
        The errors are:
        %s
        ### Assistant: I'll help fix the code. I'll provide:
        1. Error explanation in markdown
        2. Fixed code in ```java blocks
        """.formatted(javaClassContent, errorMessage);
  }





  /**
   * Builds a PromptContext based on the provided prompt and the model's prompt support capabilities.
   *
   * If the model supports prompts, it adds a system message to instruct the model to explain
   * and improve Java code errors, and a user message containing the provided prompt.
   * Otherwise, it creates a default PromptContext with the given prompt.
   *
   * @param prompt the user-provided input to create the prompt context
   * @param model the model used to verify prompt support and build the context
   * @return a constructed PromptContext based on the provided input and model's capabilities
   */
  private PromptContext buildPromptContext(String prompt, AbstractModel model) {
    if (model.promptSupport().isPresent()) {
      LOG.info("Le prompt : " + prompt);
      return model.promptSupport()
              .get()
              .builder()
              .addSystemMessage("""
               """)
              .addUserMessage(prompt)
              .build();
    }
    return PromptContext.of(prompt);
  }


  public AbstractModel getModelByName(String modelName) {
    for (var type : ModelType.values()) {
      if (type.name().equalsIgnoreCase(modelName)) {
        LOG.warning("Model : loaded is " + modelName);
        return loadedModels.get(type);
      }
    }

    LOG.warning("Model not found for name: " + modelName);
    return null;
  }

  private String buildPrompt(UserCompilerPayload userCompilerPayload) {
    if (userCompilerPayload == null) {
      throw new IllegalArgumentException("UserCompilerPayload ne peut pas être null.");
    }
    var userMessage = userCompilerPayload.userMessage();
    var compilerErrors = userCompilerPayload.compilerErrors() != null ? userCompilerPayload.compilerErrors() : "";
    var model = userCompilerPayload.model();
    return switch (model) {
        case "MISTRAL_7B" -> buildMistralPrompt(userMessage, compilerErrors);
        case "Yi_Coder" -> buildYiCoderPrompt(userMessage, compilerErrors);
        case "Llama_32" -> buildLlamaPrompt(userMessage, compilerErrors);
        default -> throw new IllegalStateException("Modèle non pris en charge : " + currentModel);
    };
  }

  /**
   * Generates a response stream by processing a user's input and compiler error details
   * using a large language model (LLM). The results are asynchronously streamed back to
   * the client through the provided WebSocket session.
   *
   * @param userCompilerPayload an object containing the user's input message and the associated
   *                             compiler error details. Used to construct the prompt for the LLM.
   *                             Must not be null.
   * @param session the WebSocket session used to send the generated response tokens back to the client.
   *                Must be open before invoking this method to ensure successful communication.
   * @throws IOException if an I/O error occurs while sending messages through the WebSocket session.
   * @throws IllegalStateException if the current model is not initialized or loaded into memory.
   */
  public void generateResponseStream(UserCompilerPayload userCompilerPayload, Session session) throws IOException {
    var model = getModelByName(userCompilerPayload.model());
    if (model == null) {
      throw new IllegalStateException("Model not initialized");
    }

    llmExecutor.submit(() -> {
      LOG.info("nameClass: " + userCompilerPayload.userMessage());
      LOG.info("question: " + userCompilerPayload.compilerErrors());

      String prompt = buildPrompt(userCompilerPayload);
      PromptContext ctx = buildPromptContext(prompt, model);

      model.generate(
              UUID.randomUUID(),
              ctx,
              temperature,
              maxTokens,
              (token, progress) -> {
                if (session.isOpen()) {
                  session.getAsyncRemote().sendText(token); // Envoi direct
                }
              }
      );
      session.getAsyncRemote().sendText("[END]"); // Fin de transmission
    });
  }

  @PreDestroy
  public void shutdownExecutors() {
    LOG.info("Shutting down ExecutorService...");
    llmExecutor.shutdown();
    LOG.info("ExecutorService shutdown complete.");
  }

}
