# Propriétés JSON
quarkus.jackson.fail-on-unknown-properties=false

# Configuration de Quinoa (Frontend)
quarkus.quinoa.ui-dir=src/main/webui
quarkus.quinoa.package-manager=npm
quarkus.quinoa.package-manager-install.node-version=22.9.0
quarkus.quinoa.build-dir=dist
quarkus.quinoa.enable-spa-routing=true

# Configuration HTTP
quarkus.http.cors=true
quarkus.http.cors.origins=/.*/
quarkus.http.root-path=/
quarkus.http.non-application-root-path=/

# Base de données (https://quarkus.io/guides/datasource#other-databases)
quarkus.datasource.db-kind=hsqldb
quarkus.datasource.username=sa
quarkus.datasource.password=
quarkus.datasource.jdbc.url=jdbc:hsqldb:file:demands;shutdown=true
quarkus.datasource.jdbc.max-size=32
quarkus.datasource.jdbc.driver=org.hsqldb.jdbc.JDBCDriver
quarkus.datasource.devservices.enabled=false
quarkus.datasource.jdbc.enable-metrics=true
quarkus.datasource.jdbc.detect-statement-leaks=false

# Configuration des tests
%test.quarkus.hibernate-orm.database.generation=drop-and-create
%test.quarkus.datasource.db-kind=hsqldb
%test.quarkus.datasource.jdbc.url=jdbc:hsqldb:file:testdb
%test.quarkus.datasource.username=sa
%test.quarkus.datasource.password=

# Configuration des threads
quarkus.thread-pool.max-threads=200

# Configuration des packages
quarkus.package.jar.enabled=true
quarkus.package.jar.type=uber-jar

# Propriétés supplémentaires pour les llm
llm.max.tokens=900
llm.temperature=0.5
